use spaces

diff --git a/src/.local/bin/ext b/src/.local/bin/ext
--- a/src/.local/bin/ext
+++ b/src/.local/bin/ext
@@ -7,40 +7,40 @@
 # Behavior with `-c` option: Extract contents into current directory
 
 while getopts "hc" o; do case "${o}" in
-	c) extracthere="True" ;;
-	*) printf "Options:\\n   -c: Extract archive into current directory rather than a new one.\\n" && exit 1 ;;
+    c) extracthere="True" ;;
+    *) printf "Options:\\n   -c: Extract archive into current directory rather than a new one.\\n" && exit 1 ;;
 esac done
 
 if [ -z "$extracthere" ]; then
-	archive="$(readlink -f "$*")" &&
-	directory="$(echo "$archive" | sed 's/\.[^\/.]*$//')" &&
-	mkdir -p "$directory" &&
-	cd "$directory" || exit 1
+    archive="$(readlink -f "$*")" &&
+    directory="$(echo "$archive" | sed 's/\.[^\/.]*$//')" &&
+    mkdir -p "$directory" &&
+    cd "$directory" || exit 1
 else
-	archive="$(readlink -f "$(echo "$*" | cut -d' ' -f2)" 2>/dev/null)"
+    archive="$(readlink -f "$(echo "$*" | cut -d' ' -f2)" 2>/dev/null)"
 fi
 
 [ -z "$archive" ] && printf "Give archive to extract as argument.\\n" && exit 1
 
 if [ -f "$archive" ] ; then
-	case "$archive" in
-		*.tar.bz2|*.tbz2) bsdtar -xvf "$archive" ;;
-		*.tar.xz) bsdtar -xvf "$archive" ;;
-		*.tar.gz|*.tgz) bsdtar -xvf "$archive" ;;
-		*.tar.zst) bsdtar -xvf "$archive" ;;
-		*.tar) bsdtar -xvf "$archive" ;;
-		*.lzma) unlzma -v "$archive" ;;
-		*.bz2) bunzip2 -v "$archive" ;;
-		*.rar) unrar x -ad "$archive" ;;
-		*.gz) gunzip -v "$archive" ;;
-		*.zip) unzip -v "$archive" ;;
-		*.Z) uncompress -v "$archive" ;;
-		*.7z) 7z x "$archive" ;;
-		*.xz) unxz -v "$archive" ;;
-		*.zst) zstd -dv "$archive" ;;
-		*.exe) cabextract "$archive" ;;
-		*) printf "extract: '%s' - unknown archive method\\n" "$archive" ;;
-	esac
+    case "$archive" in
+        *.tar.bz2|*.tbz2) bsdtar -xvf "$archive" ;;
+        *.tar.xz) bsdtar -xvf "$archive" ;;
+        *.tar.gz|*.tgz) bsdtar -xvf "$archive" ;;
+        *.tar.zst) bsdtar -xvf "$archive" ;;
+        *.tar) bsdtar -xvf "$archive" ;;
+        *.lzma) unlzma -v "$archive" ;;
+        *.bz2) bunzip2 -v "$archive" ;;
+        *.rar) unrar x -ad "$archive" ;;
+        *.gz) gunzip -v "$archive" ;;
+        *.zip) unzip -v "$archive" ;;
+        *.Z) uncompress -v "$archive" ;;
+        *.7z) 7z x "$archive" ;;
+        *.xz) unxz -v "$archive" ;;
+        *.zst) zstd -dv "$archive" ;;
+        *.exe) cabextract "$archive" ;;
+        *) printf "extract: '%s' - unknown archive method\\n" "$archive" ;;
+    esac
 else
-	printf "File \"%s\" not found.\\n" "$archive"
+    printf "File \"%s\" not found.\\n" "$archive"
 fi
