replace mount and unmount scripts with luke's

diff --git a/src/.local/bin/menumount b/src/.local/bin/menumount
--- a/src/.local/bin/menumount
+++ b/src/.local/bin/menumount
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # Gives a menu prompt to mount unmounted drives and Android phones. If
 # they're in /etc/fstab, they'll be mounted automatically. Otherwise, you'll
@@ -7,62 +7,109 @@
 
 menu="$MENU -p"
 
-getmount() {
-	[ -z "$chosen" ] && exit 1
-	mp="$(find $1 2>/dev/null | $menu "Type in mount point.")" || exit 1
-	[ "$mp" = "" ] && exit 1
-	if [ ! -d "$mp" ]; then
-		mkdiryn=$(prompt "$mp does not exist. Create it?" "echo Yes")
-		[ "$mkdiryn" = "Yes" ] && (mkdir -p "$mp" || sudo -A mkdir -p "$mp")
-	fi
-	}
+# Function for escaping cell-phone names.
+escape(){ echo "$@" | iconv -cf UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed "s/-\+/-/g;s/\(^-\|-\$\)//g" ;}
 
-mountusb() { \
-	chosen="$(echo "$usbdrives" | $menu "Mount which drive?")" || exit 1
-	chosen="$(echo "$chosen" | awk '{print $1}')"
-	sudo -A mount "$chosen" 2>/dev/null && notify-send "💻 USB mounting" "$chosen mounted." && exit 0
-	alreadymounted=$(lsblk -nrpo "name,type,mountpoint" | awk '$3!~/\/boot|\/home$|SWAP/&&length($3)>1{printf "-not ( -path *%s -prune ) ",$3}')
-	getmount "/mnt /media /mount /home -maxdepth 5 -type d $alreadymounted"
-	partitiontype="$(lsblk -no "fstype" "$chosen")"
-	case "$partitiontype" in
-		"vfat") sudo -A mount -t vfat "$chosen" "$mp" -o rw,umask=0000;;
-		"exfat") sudo -A mount "$chosen" "$mp" -o uid="$(id -u)",gid="$(id -g)";;
-		*) sudo -A mount "$chosen" "$mp"; user="$(whoami)"; ug="$(groups | awk '{print $1}')"; sudo -A chown "$user":"$ug" "$mp";;
-	esac
-	notify-send "💻 USB mounting" "$chosen mounted to $mp."
-	}
+# Check for phones.
+phones="$(simple-mtpfs -l 2>/dev/null | sed "s/^/📱/")"
+mountedphones="$(grep "simple-mtpfs" /etc/mtab)"
+# alreadymounted=$(lsblk -nrpo "name,type,mountpoint" | awk '$3!~/\/boot|\/home$|SWAP/&&length($3)>1{printf "-not ( -path *%s -prune ) ",$3}')
 
-mountandroid() {
-	chosen="$(echo "$anddrives" | $menu "Which Android device?")" || exit 1
-	chosen="$(echo "$chosen" | cut -d : -f 1)"
-	getmount "$HOME -maxdepth 3 -type d"
-	simple-mtpfs --device "$chosen" "$mp"
-	echo "OK" | $menu "Tap Allow on your phone if it asks for permission and then press enter" || exit 1
-	simple-mtpfs --device "$chosen" "$mp"
-	notify-send "🤖 Android Mounting" "Android device mounted to $mp."
-	}
+# If there are already mounted phones, remove them from the list of mountables.
+[ -n "$mountedphones" ] && phones="$(for phone in $phones; do
+for mounted in $mountedphones; do
+    escphone="$(escape "$phone")"
+    [[ "$mounted" =~ "$escphone" ]] && break 1
+done && continue 1
+echo "$phone"
+done)"
 
-asktype() { \
-	choice="$(printf "USB\\nAndroid" | $menu "Mount a USB drive or Android device?")" || exit 1
-	case $choice in
-		USB) mountusb ;;
-		Android) mountandroid ;;
-	esac
-	}
+# Check for drives.
+lsblkoutput="$(lsblk -rpo "uuid,name,type,size,label,mountpoint,fstype")"
+# Get all LUKS drives
+allluks="$(echo "$lsblkoutput" | grep crypto_LUKS)"
+# Get a list of the LUKS drive UUIDs already decrypted.
+decrypted="$(find /dev/disk/by-id/dm-uuid-CRYPT-LUKS2-* | sed "s|.*LUKS2-||;s|-.*||")"
+# Functioning for formatting drives correctly for menu:
+filter() { sed "s/ /:/g" | awk -F':' '$7==""{printf "%s%s (%s) %s\n",$1,$3,$5,$6}' ; }
 
-anddrives=$(simple-mtpfs -l 2>/dev/null)
-usbdrives="$(lsblk -rpo "name,type,size,mountpoint" | grep 'part\|rom' | awk '$4==""{printf "%s (%s)\n",$1,$3}')"
+# Get only LUKS drives that are not decrypted.
+unopenedluks="$(for drive in $allluks; do
+uuid="${drive%% *}"
+uuid="${uuid//-}"	# This is a bashism.
+for open in $decrypted; do
+    [ "$uuid" = "$open" ] && break 1
+done && continue 1
+echo "🔒 $drive"
+done | filter)"
 
-if [ -z "$usbdrives" ]; then
-	[ -z "$anddrives" ] && echo "No USB drive or Android device detected" && exit
-	echo "Android device(s) detected."
-	mountandroid
-else
-	if [ -z "$anddrives" ]; then
-		echo "USB drive(s) detected."
-		mountusb
-	else
-		echo "Mountable USB drive(s) and Android device(s) detected."
-		asktype
-	fi
-fi
+# Get all normal, non-encrypted or decrypted partitions that are not mounted.
+normalparts="$(echo "$lsblkoutput"| grep -v crypto_LUKS | grep 'part\|rom\|crypt' | sed "s/^/💾 /" | filter )"
+
+# Add all to one variable. If no mountable drives found, exit.
+alldrives="$(echo "$phones
+$unopenedluks
+$normalparts" | sed "/^$/d;s/ *$//")"
+
+# Quit the script if a sequential command fails.
+set -e
+
+test -n "$alldrives"
+
+# Feed all found drives to menu and get user choice.
+chosen="$(echo "$alldrives" | $menu "Mount which drive?" -i)"
+
+# Function for prompting user for a mountpoint.
+getmount(){
+    mp="$(find /mnt /media /mount /home -maxdepth 5 -type d 2>/dev/null | $menu "Mount this drive where?")"
+    test -n "$mp"
+    if [ ! -d "$mp" ]; then
+        mkdiryn=$(printf "No\\nYes" | $menu "$mp does not exist. Create it?")
+        [ "$mkdiryn" = "Yes" ] && (mkdir -p "$mp" || sudo -A mkdir -p "$mp")
+    fi
+}
+
+attemptmount(){
+    # Attempt to mount without a mountpoint, to see if drive is in fstab.
+    sudo -A mount "$chosen" || return 1
+    notify-send "💾Drive Mounted." "$chosen mounted."
+    exit
+}
+
+case "$chosen" in
+    💾*)
+        chosen="${chosen%% *}"
+        chosen="${chosen:1}"	# This is a bashism.
+        attemptmount || getmount
+        sudo -A mount "$chosen" "$mp" -o uid="$(id -u)",gid="$(id -g)"
+        notify-send "💾Drive Mounted." "$chosen mounted to $mp."
+        ;;
+
+    🔒*)
+        chosen="${chosen%% *}"
+        chosen="${chosen:1}"	# This is a bashism.
+        # Number the drive.
+        while true; do
+            [ -f "/dev/mapper/usb$num" ] || break
+            num="$(printf "%02d" "$((num +1))")"
+        done
+
+        # Decrypt in a terminal window
+        ${TERMINAL:-st} -n floatterm -g 60x1 -e sudo cryptsetup open "$chosen" "usb$num"
+        # Check if now decrypted.
+        test -b "/dev/mapper/usb$num"
+
+        attemptmount || getmount
+        sudo -A mount "/dev/mapper/usb$num" "$mp" -o uid="$(id -u)",gid="$(id -g)"
+        notify-send "🔓Decrypted drive Mounted." "$chosen decrypted and mounted to $mp."
+        ;;
+
+    📱*)
+        notify-send "❗Note" "Remember to allow file access on your phone now."
+        getmount
+        number="${chosen%%:*}"
+        number="${chosen:1}"	# This is a bashism.
+        sudo -A simple-mtpfs -o allow_other -o fsname="simple-mtpfs-$(escape "$chosen")" --device "$number" "$mp"
+        notify-send "🤖 Android Mounted." "Android device mounted to $mp."
+        ;;
+esac
